spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: hookedApi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        security:
          web: trace