name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/*.jar
          target: /home/ubuntu/hooked-api/

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/hooked-api

            # 최초 배포 시 Git 설정
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/LeeSeungChan-1/hookedApi.git
            fi

            # 최신 커밋 동기화
            git fetch origin master
            git reset --hard origin/master

            # 환경 파일은 서버에서 별도로 관리합니다
            echo "[INFO] Using server-managed .env, skipping copy"

            # 애플리케이션 재시작
            pkill -f 'hooked-api' || true
            nohup java -jar *.jar --spring.profiles.active=production > hooked-api.log 2>&1 &