# .github/workflows/deploy.yml
name: Build & Deploy hookedApi to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - name: Checkout hookedApi
        uses: actions/checkout@v3

      # 2) JDK 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3) Gradle wrapper에 실행 권한 부여
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 4) Gradle clean & bootJar 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar --no-daemon

      # 5) 빌드된 JAR을 EC2로 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: build/libs/*.jar
          target: /home/${{ secrets.EC2_USER }}/hookedApi/

      # 6a) EC2에서 .env 생성 및 기존 프로세스 종료
      - name: Prepare env and stop old process
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          command_timeout: 2m
          script: |
            cd /home/${{ secrets.EC2_USER }}/hookedApi
            cat > .env <<EOF
            DB_URL=${{ secrets.DB_URL }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF
            pkill -f 'hookedApi.*\.jar' || true

      # 6b) EC2에서 새 JAR 백그라운드 실행
      - name: Start new hookedApi process
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          command_timeout: 2m
          script: |
            cd /home/${{ secrets.EC2_USER }}/hookedApi
            nohup java -jar *.jar > app.log 2>&1 &

