# .github/workflows/deploy.yml
name: Build & Deploy hookedApi to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1) 리포지토리 체크아웃
      - name: Checkout hookedApi
        uses: actions/checkout@v3

      # 2) JDK 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3) Gradle wrapper에 실행 권한 부여
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 4) Gradle clean & bootJar 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar --no-daemon

      # 5) 빌드된 JAR을 EC2로 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: build/libs/*.jar
          target: /home/${{ secrets.EC2_USER }}/hookedApi/

      # 6) SSH 에이전트에 키 로드
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 7) 직접 ssh 로 원격 명령 실행
      - name: Deploy on EC2 via ssh
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.EC2_SSH_PORT }} \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
            # 1) 작업 디렉터리 이동
            cd /home/${{ secrets.EC2_USER }}/hookedApi

            # 2) .env 파일 생성
            cat > .env <<EOV
            DB_URL=${{ secrets.DB_URL }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOV

            # 3) 기존 프로세스 종료
            pkill -f 'hookedApi.*\.jar' || true

            # 4) 새 JAR 백그라운드 실행
            nohup java -jar *.jar > app.log 2>&1 &
          EOF
