name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/*.jar
          target: /home/ubuntu/hooked-api/

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure deployment directory exists
            mkdir -p /home/ubuntu/hooked-api
            cd /home/ubuntu/hooked-api

            # Clean up old JARs
            rm -f *.jar

            # Move new JAR into place (if scp didn't overwrite existing files)
            mv *.jar hooked-api.jar || true

            # Start new JAR in background, logs to file
            nohup java -jar hooked-api.jar --spring.profiles.active=production > hooked-api.log 2>&1 &
